FUNCTION "LMAxisCtrlApcFr_Enable" : Void
{ S7_Optimized_Access := 'TRUE' }
VERSION : 0.1
   VAR_INPUT 
      Enable : Bool;
   END_VAR

   VAR_IN_OUT 
      AxisFB_Interface : "LMAxisCtrlApcFr_TypeInterface";
   END_VAR


BEGIN
	//=====================================================================================================
	#AxisFB_Interface.In.enable := #Enable;
	//=====================================================================================================
END_FUNCTION

